kind: pipeline
name: Build_1

steps:
  - name: test_1
    image: perl
    environment:
      COVERALLS_REPO_TOKEN:
        from_secret: COVERALLS_REPO_TOKEN
      COVERALLS_FLAG_NAME: test1
    commands:
      - cpanm --quiet --installdeps --notest .
      - perl Build.PL build && ./Build
      - PERL5LIB=blib/lib cover -test -silent -select ^t -report coveralls
---
kind: pipeline
name: Build_2

steps:
  - name: test_2
    image: perl
    environment:
      COVERALLS_REPO_TOKEN:
        from_secret: COVERALLS_REPO_TOKEN
      COVERALLS_FLAG_NAME: test2
    commands:
      - cpanm --quiet --installdeps --notest .
      - perl Build.PL build && ./Build
      - PERL5LIB=blib/lib cover -test -silent -select ^t -report coveralls
---

kind: pipeline
name: Coveralls_webhook_done

steps:
  - name: send_done2
    image: plugins/webhook
    environment:
      COVERALLS_REPO_TOKEN:
        from_secret: COVERALLS_REPO_TOKEN
    settings:
      urls: https://coveralls.io/webhook?repo_token=${COVERALLS_REPO_TOKEN}
      content_type: application/json
      template: |
        {
          "payload": {
            "build_num": ${DRONE_BUILD_NUMBER},
            "status": "done"
          }
        }
depends_on:
  - Build_1
  - Build_2
